name: <your project name>
services:
    campsite_checker_ab:
        ports:
            - 6901:6901
            - 5901:5901
        environment:
            - ENV_URL=https://shop.albertaparks.ca/camping/chinook-provincial-recreation-area/r/campgroundDetails.do?contractCode=ABPP&parkId=330293#sr_a
            - ENV_APIURL=
            - ENV_TOKEN=
            - ENV_CHATID=
            - ENV_DELAY=5
        cap_add:
            - SYS_ADMIN
        container_name: campsite_checker_bc
        image: campsite_checker_bc